preguntas_graciosas = [
                    "¿En qué estás pensando? ¿Bug o feature?",
                    "¿Por qué el café en la oficina nunca alcanza?",
                    "Si fueras un lenguaje de programación, ¿serías Python o un legacy en Java?",
                    "¿Alguna vez hablaste con tu código para convencerlo de que no falle?",
                    "¿Por qué los semáforos no tienen modo ‘modo debug’ para cuando andan lentos?",
                    "¿Te pasó que el deploy anda bien en local y en producción te llora todo?",
                    "Si te dieran un peso por cada error 404, ¿vivirías en Miami?",
                    "¿En serio usás tabs o sos de los que ponen espacios para molestar?",
                    "¿El compilador te entiende o también le tirás ‘qué onda’ cuando falla?",
                    "¿Alguna vez escribiste código que funcione a la primera? ¿O sos un unicornio?",
                    "¿Qué onda, te gusta más programar de noche o cuando estás re cansado?",
                    "¿El cliente pidió ‘solo un cambio’ y terminó cambiando todo el proyecto, no?",
                    "¿Te sentís un mago cuando tu código anda sin errores… por cinco minutos?",
                    "¿Sos más de Stack Overflow o de Googlear hasta que aparece la respuesta?",
                    "¿Cuántos mates se necesitan para entender ese algoritmo?",
                    "¿Qué preferís: depurar código o ir a la verdulería un sábado a la mañana?",
                    "Si tu código fuera un asado, ¿estaría jugoso o seco como el desierto?",
                    "¿Alguna vez usaste `print('Hola mundo')` para convencer a alguien que sabés programar?",
                    "¿Sos más de comentarios copados o de dejar todo críptico para que el próximo sufra?",
                    "¿Qué es peor: un merge conflict o que te falte café?",
                    "¿Probaste apagar y prender el router... emocional?",
                    "¿Cuántas líneas de código se necesitan para olvidarse de un ex?",
                    "¿Te pasó que arreglaste un bug y aparecieron dos nuevos, tipo Hidra de Marvel?",
                    "¿Debugueás o hacés 'prueba y error con fe' como buen developer argentino?",
                    "¿Por qué los lunes duran más que un `while(true)` sin break?",
                    "¿Cuál fue tu momento más ‘yo robot’ frente al teclado?",
                    "¿Sos más de cerrar el editor con dignidad o de ragequit con ALT+F4?",
                    "¿Tu código tiene más parches que una campera vieja del Once?",
                    "¿Tenés más commits que horas de sueño?",
                    "¿Para vos ‘refactorizar’ es sinónimo de ‘me cansé y empecé de cero’?",
                    "¿Cuántas veces por semana renegás con un `null` que no debería ser null?",
                    "¿Tu código compila o lo tenés amenazado con mates y promesas?",
                    "¿Cuánto tarda tu compu en levantar el proyecto? ¿Más que un colectivo en hora pico?",
                    "¿Alguna vez lloraste porque el error era un punto y coma faltante?",
                    "¿Sos de los que programan con música de cumbia, rock nacional o silencio místico?",
                    "¿Tenés más tabs abiertos que ganas de vivir?",
                    "¿Te considerás full stack o full quemado?",
                    "¿Ya está listo el proyecto o sigue en 'etapa de pulido' desde el 2021?",
                    "¿Si fueras un Jedi, debuguearías con la Fuerza o con `console.log`?",
                    "¿Cuántas veces por semana sentís que estás en un loop temporal tipo ‘Día de la marmota’, pero con bugs?",
                    "¿En qué momento exacto tu código se convirtió en algo más oscuro que el Anillo Único?",
                    "¿Programás como Batman: de noche, solo y con trauma incluido?",
                    "¿Sos más Tony Stark o Peter Parker con el código?",
                    "¿El repo de tu proyecto parece el multiverso de Loki?",
                    "¿Cuántos commits necesitás para que tu código deje de comportarse como Gollum?",
                    "¿Te sentís más Thanos antes o después del `npm install`?",
                    "¿Debuguearías a HAL 9000 o preferís no tocar nada y vivir?",
                    "¿Te das cuenta que programar a veces es como vivir en Matrix pero sin poderes?",
                    "¿Si el sistema fuera la Estrella de la Muerte, vos sos Darth Vader o un stormtrooper más?",
                    "¿Alguna vez tu código te respondió con 'Soy tu padre'?",
                    "¿Preferís compilar un proyecto viejo o cruzarte con un dementor en el bondi?",
                    "¿Tenés más tabs abiertos que líneas de diálogo en ‘El Señor de los Anillos’?",
                    "¿Alguna vez deseaste que R2-D2 arregle tu base de datos solo?",
                    "¿Sos más House Stark, House Lannister o House Stack Overflow?",
                    "¿Te pasó de mirar un error como si fuera el laberinto de Inception?",
                    "¿Programás en modo John Wick: enfocado, silencioso, y con algo de venganza?",
                    "¿Te sentís como Neo cuando por fin entendés por qué fallaba ese if?",
                    "¿Alguna vez soñaste que estabas programando y funcionaba todo? ¿O solo en tus fanfics?",
                    "¿Tu código es más complejo que la trama de Evangelion?",
                    "¿Sos más de debuguear como Goku: a las piñas y con fe?",
                    "¿Ese bug que no podés encontrar… es tu verdadero enemigo, Itachi?",
                    "¿Tu framework tiene más transformaciones que Freezer?",
                    "¿Alguna vez programaste con tanto estrés que te sentiste en el examen Chunin?",
                    "¿Cuando no entendés qué hace el código, decís ‘NANI?!’ como buen otaku?",
                    "¿Cuánto falta para que tu proyecto tenga su propio arco filler?",
                    "¿Ese error que vuelve una y otra vez… es un Jutsu Prohibido?",
                    "¿Te sentís más como Light con la Death Note o como L, resolviendo bugs?",
                    "¿Cuántos capítulos de tu vida llevás intentando centrar un div?",
                    "¿Ese código lo hiciste vos o es una técnica secreta de la aldea oculta entre los bugs?",
                    "¿Sos más de usar ‘for’ como un ataque directo tipo Kamehameha o de estrategias raras como un JoJo?",
                    "¿Ese if tiene sentido… o es una ilusión de Aizen?",
                    "¿Tu CSS se descontrola más que un Titán en plena ciudad?",
                    "¿Tus ganas de programar hoy están en modo ‘Shinji subite al Eva’?",
                    "¿Qué tan roto está tu proyecto? ¿Nivel Saitama o Krilin con mala suerte?",
                    "¿Alguna vez te sentiste el protagonista solo porque hiciste andar algo a la primera?",
                    "¿Tu deploy es más impredecible que el final de un anime psicológico?",
                    "¿El backend que te tocó heredar… es el verdadero villano del arco?",
                    "¿Tu editor de código está tan lleno de extensiones como el equipo de la U.A. de Boku no Hero?",
                    "¿Tu código compila o le tenés que tirar una poción de maná?",
                    "¿Cuántos bugs tenés que matar para subir de nivel como programador?",
                    "¿Ese error es un mini boss o un jefe final al estilo Dark Souls?",
                    "¿Programás en easy, normal o modo pesadilla sin guardar?",
                    "¿Tu deploy fue exitoso o explotó como un creeper de Minecraft?",
                    "¿Tu base de datos se rompe más fácil que un escudo en Fortnite?",
                    "¿Tus commits tienen más historia que el lore de Zelda?",
                    "¿Hoy vas a trabajar… o vas a hacer AFK espiritual?",
                    "¿Ese bug es un glitch o ya es parte del gameplay?",
                    "¿Sentís que tu código es un sandbox o una prisión sin salida?",
                    "¿Cuando hacés merge, lo hacés con stealth o con full ataque como en Doom?",
                    "¿Alguna vez perdiste todo por no hacer un `git save`? ¿O sólo en The Sims?",
                    "¿Tenés tantos archivos abiertos como ítems en tu inventario de Skyrim?",
                    "¿Ese código es open world o más guiado que un tutorial de Pokémon?",
                    "¿Tu framework está optimizado o corre como si tuviera lag de servidor ruso?",
                    "¿Sentís que el cliente juega en modo PvP con tus plazos?",
                    "¿Si tu sprint fuera una partida, ya estarías en la pantalla de ‘Game Over’?",
                    "¿Tu código es como Tetris: encajando milagrosamente o ya colapsó todo?",
                    "¿Alguna vez soñaste con hacer un deploy perfecto, o eso es un final alternativo?",
                    "¿Sos team teclado mecánico ruidoso o jugás con mouse prestado nivel 1?",
                    "¿Tu amor es recursivo o sólo entra en bucle cuando te veo?",
                    "¿Te animás a un `git commit --amour`?",
                    "¿Sos una excepción en mi try, pero igual te capturo.",
                    "¿Sos tú o mi corazón tiene memory leak?",
                    "¿Podemos hacer un merge sin conflictos?",
                    "¿Me estás rompiendo el sistema o solo el corazón?",
                    "¿Puedo ser el div que contenga tu universo?",
                    "¿Este crush es real o sólo está en staging?",
                    "¿Querés ser mi variable global para siempre?",
                    "¿Esto que siento es una función pura o tiene side effects?",
                    "¿Nos hacemos deploy juntos o cada uno en su entorno?",
                    "¿Querés ser mi .env y guardar mis secretos?",
                    "¿Ese beso fue un feature o un bug que no quiero arreglar?",
                    "¿Querés declarar una relación en el schema de mi corazón?",
                    "¿Estamos bien tipeados o hace falta un casting emocional?",
                    "¿Te animás a un `sudo love` sin permisos?",
                    "¿Esto que siento se testea con integración o con tiempo?",
                    "¿Nuestro amor tiene CI/CD o hay que deployarlo a mano?",
                    "¿Te alojás en mi servidor o preferís tu propia nube?",
                    "¿Estás en mi JSON o fue solo un sueño en formato YAML?",
                    "¿Si un código se rompe en el bosque y nadie lo ve, da error?",
                    "¿Cuántos commits se necesitan para cambiar una bombita de luz?",
                    "¿Por qué no hay frameworks para freír empanadas?",
                    "¿Y si el `console.log` es en realidad un grito de ayuda?",
                    "¿Puedo instanciar un fernet con `new Fernet()`?",
                    "¿Cuántos backends caben en un colectivo lleno de testers?",
                    "¿El CSS sueña con ovejas que se alinean en flex?",
                    "¿Si un bug se esconde debajo de la cama, quién lo debuguea?",
                    "¿Mi RAM llora cuando abro 23 pestañas con Stack Overflow?",
                    "¿Por qué mi cafetera no hace push al repo?",
                    "¿Puedo importar felicidad desde 'vida.realidad'?",
                    "¿Es legal imprimir galletitas desde una API?",
                    "¿Dónde está el botón para pausar la vida y recargar energía?",
                    "¿Puedo subir mi autoestima a la nube?",
                    "¿Si borro el historial de errores, viví sin fallas?",
                    "¿Y si todo esto es sólo un breakpoint mal puesto?",
                    "¿Podemos usar `npm install calma`?",
                    "¿El mate entra en el sprint o va a la backlog?",
                    "¿Una variable feliz es constante o mutable?",
                    "¿Si digo 'Hola Mundo' muy fuerte, compila el universo?",
                    "¿Tenés el mic en mute o es que ya no querés hablar con nadie?",
                    "¿Hoy toca trabajar o mirar la pantalla hasta que parezca trabajo?",
                    "¿Esa daily era necesaria o solo una excusa para verte bostezar?",
                    "¿Hace cuánto no apagás la compu por completo?",
                    "¿Tu silla tiene más horas sentada que vos despierto?",
                    "¿La última vez que saliste fue a tirar la basura, no?",
                    "¿El jefe te mandó un emoji o fue una amenaza pasivo-agresiva?",
                    "¿Por qué el Excel del otro monitor me juzga?",
                    "¿Hoy la VPN anda o juega a esconderse como tus ganas de laburar?",
                    "¿Trabajás en equipo o cada uno hace lo que puede y reza?",
                    "¿Si borro el error, desaparece mi dolor?",
                    "¿En qué momento un bug deja de ser error y se convierte en legado?",
                    "¿Qué sentido tiene el código si nadie lo entiende?",
                    "¿Soy yo el que programa o el código me programa a mí?",
                    "¿La vida es síncrona o siempre estamos en espera?",
                    "¿Por qué todo lo bueno está en beta?",
                    "¿Los comentarios del código son realmente sinceros?",
                    "¿Qué versión de mí mismo estoy deployando hoy?",
                    "¿Existe el código perfecto o es solo un ideal platónico?",
                    "¿Y si el debugger es en realidad un filósofo con breakpoints?",
                    "¿Qué nos hace humanos: pensar, sentir, o renombrar variables?",
                    "¿En qué commit se perdió la felicidad?",
                    "¿Cuántos pull requests necesita el alma para sanar?",
                    "¿Por qué el universo no tiene documentación oficial?",
                    "¿De qué sirve compilar si no te comparten el output?",
                    "¿La conciencia es solo un `if` mal indentado?",
                    "¿Hay vida más allá del deadline?",
                    "¿Estamos todos atrapados en un for infinito?",
                    "¿El karma se versiona con git o con el paso del tiempo?",
                    "¿La procrastinación es solo un feature no documentado del ser humano?",
                    "¿Estás bien o estás haciendo un Ross gritando 'we were on a break' al código?",
                    "¿Sos más tipo Sheldon optimizando tus emociones o Leonard intentando no romper producción?",
                    "¿Te sentís como Eleven: con poder, pero sangrando por debuggear?",
                    "¿Ya apareció tu Dark Mode o seguís atrapado en Winden?",
                    "¿Hoy tu vida es más Stranger Things o Breaking Code?",
                    "¿Te sentís más como un Dunder Mifflin o una startup con Wi-Fi trucho?",
                    "¿Tu motivación está en Netflix o en un commit milagroso?",
                    "¿Este bug vino con guión de los hermanos Duffer?",
                    "¿Sentís que tu jefe es Walter White diciendo 'I am the danger'?",
                    "¿Tenés más problemas que los timelines de Marvel?",
                    "¿Hoy sos más Mandalorian o te cancelaron como Boba Fett?",
                    "¿Ese código es tu 'HIMYM' o ya sabés que no termina bien?",
                    "¿Estás laburando o maratoneando mentalmente The Office?",
                    "¿Sos más Daenerys conquistando código o Jon Snow sin saber nada?",
                    "¿Tus variables son como los personajes de Lost: sin rumbo?",
                    "¿Estás bien o ya estás escuchando el opening de Malcolm in the Middle en loop?",
                    "¿Tus tests pasan o se rinden como Ned Stark en producción?",
                    "¿Esta entrega la hiciste vos o fue un multiverso con mejores decisiones?",
                    "¿Tu repo está más desordenado que un episodio de Rick and Morty?",
                    "¿Sos más Loki: mentiroso, dios del caos, pero igual crack del código?",
                    "¿Tu motivación se fue con el último commit del viernes?",
                    "¿Estás en burnout o simplemente en modo ahorro de energía?",
                    "¿Ese 'funciona en mi máquina' ya es tu religión?",
                    "¿Cuánto debug necesitás para reencontrarte con vos mismo?",
                    "¿La vida es dura o es solo otro sprint sin sentido?",
                    "¿Tus ganas de trabajar están en staging?",
                    "¿Tu autoestima baja con cada pull request rechazado?",
                    "¿Ese refactor te rompió el alma o solo la estructura del proyecto?",
                    "¿Estás seguro que querés seguir siendo developer o ya pensaste en ser barista?",
                    "¿Tus commits tienen más lágrimas que líneas de código?",
                    "¿Qué pasa si acepto todos los cambios sin mirar?",
                    "¿Y si la consola no está rota, sino triste?",
                    "¿Qué es más difícil: entender Redux o tus sentimientos?",
                    "¿Un junior puede llorar en JSON?",
                    "¿Cuántos print() hacen falta para iluminar el camino del backend?",
                    "¿Dónde van los bugs cuando nadie los busca?",
                    "¿Un test que nunca falla realmente está vivo?",
                    "¿Si un front grita en el bosque, el backend lo escucha?",
                    "¿Y si este error no es mío sino del universo?",
                    "¿Las ideas se versionan o simplemente cambian de branch?",
                    "¿Cuál es el sonido de un deploy que no rompe nada?",
                    "¿Un commit sin mensaje tiene alma?",
                    "¿Puedo importar cordura desde otro módulo?",
                    "¿La vida tiene un linter moral?",
                    "¿Es posible hacer rollback a una decisión de vida?",
                    "¿Estás casteando hechizos o solo un `int` mal tipeado?",
                    "¿Tu IDE es la Espada de Gryffindor o una piedra filosofal con bugs?",
                    "¿Sos el elegido o simplemente otro padawan con dudas?",
                    "¿Tu repo está guardado en la Fortaleza de la Soledad?",
                    "¿Y si tu código es en realidad el One Ring?",
                    "¿Ya llamaste al mago del deploy o seguís probando solo?",
                    "¿Tu sprint viene con dragones o solo orcos en Jira?",
                    "¿Vivís en el backend o en una dimensión paralela como Doctor Strange?",
                    "¿Sos un Jedi del código o solo usás `force push`?",
                    "¿Quién dejó a un hobbit tocando el servidor?",
                    "¿Ya fuiste a Mordor o tu producción tiene SSL?",
                    "¿Tus endpoints viajan en el tiempo como Marty McFly?",
                    "¿La base de datos está viva o es un Dementor con índices mal puestos?",
                    "¿Tus commits tienen más épica que una campaña de D&D?",
                    "¿Y si estamos todos dentro de una simulación en React?",
                    "¿El CSS te odia o simplemente viene de otro plano astral?",
                    "¿Tus deploys son tan místicos como la profecía de Elrond?",
                    "¿Tenés la piedra del tiempo o solo ganas de dormir?",
                    "¿El bug final está en el castillo o en tu lógica?",
                    "¿Estás más cerca del trono de hierro o de otro lunes sin feriado?",
                    "¿Tu corazón hace ping o timeout cuando la ves conectada?",
                    "¿Sos main tanque en la vida real también o solo en el LoL?",
                    "¿Esa cara es por bugs o porque alguien te spoileó One Piece?",
                    "¿Quién sos sin tu café y sin tus extensiones del VSCode?",
                    "¿Y si los errores 500 también sienten culpa?",
                    "¿Tus sueños compilan o tienen conflictos con el subconsciente?",
                    "¿Estás esperando el deploy... o al amor de tu vida?",
                    "¿Te dejaron en visto o es un problema de latencia emocional?",
                    "¿Cuántos commits necesitás para cerrar ese vacío existencial?",
                    "¿Sos de los que responden mails como hechicero de nivel 2 o más bien como Gollum?",
                    "¿Si pierdo contra un bot en el FIFA, me quitan el Wi-Fi del honor?",
                    "¿Estás en standup o simplemente parado frente a tus errores?",
                    "¿El problema era el código o simplemente no dormiste bien desde 2022?",
                    "¿Esa query es lenta o solo tiene problemas de confianza?",
                    "¿La vida tiene bugs o está bien así de caótica por diseño?",
                    "¿Tus emociones están en staging o ya las mergeaste con lo real?",
                    "¿Se puede llorar en una daily sin perder dignidad?",
                    "¿Por qué no podemos simplemente vivir en la intro de Cowboy Bebop?",
                    "¿Tenés el alma rota o solo un handler mal cerrado?",
                    "¿Ese laburo remoto es remoto... o ficticio?",
                    "¿El jefe te explicó algo o solo habló en Elfico Quenya?",
                    "¿Sos el héroe de esta historia o solo un NPC en loop infinito?",
                    "¿Tus pensamientos hacen `console.log()` o `throw new Error()`?",
                    "¿La oficina es Hogwarts o Azkaban con teclado?",
                    "¿Le hablaste con amor... o con `git push --force`?",
                    "¿Ese 'nos hablamos' fue sincero o un `setTimeout()` eterno?",
                    "¿Sos más Shingeki: explotando emociones, o Pokémon: evadiendo problemas?",
                    "¿Los lunes vienen con DLC o siempre están bugueados así?",
                    "¿Tu código es open source o celoso como un sith?",
                    "¿Las reuniones eternas pueden considerarse tortura medieval?",
                    "¿Quién necesita terapia teniendo tantos memes de bugs?",
                    "¿Tus relaciones tienen más callbacks que un proyecto legacy?",
                    "¿Ese rechazo fue romántico o una excepción no controlada?",
                    "¿Le dijiste algo lindo o le corregiste el CSS?",
                    "¿La base de datos guarda sentimientos también?",
                    "¿Querés una cita o solo resolver este merge conflict juntos?",
                    "¿Estás triste o solo hiciste click en 'abrir Jira'?",
                    "¿Te sentís como el protagonista o como el bug final?",
                    "¿Sos el prota de tu anime o solo un personaje de relleno?",
                    "¿El deploy fue exitoso o sólo otra ilusión de frontend?",
                    "¿Este amor va al backlog o ya está en producción?",
                    "¿El repo es privado porque da vergüenza o por NDA emocional?",
                    "¿Tus sueños tienen semántica o son puro HTML sin CSS?",
                    "¿Hoy tocás la felicidad o solo estás usando el IDE en modo oscuro?",
                    "¿Y si en vez de debuggear tanto... dormimos 8 horas?",
                    "¿Sos el elegido para esa historia o te lo dijeron en una daily por error?",
                    "¿Podemos reiniciar el sprint como se reinicia el router?",
                    "¿Ese ‘juguemos algo’ incluye sentimientos o solo cooperativo local?",
                    "¿La vida te está trolleando o es parte del lore?",
                    "¿Vivís en el backend o en una dimensión paralela como Doctor Strange?",
                    "¿Sos un Jedi del código o solo usás `force push`?",
                    "¿Quién dejó a un hobbit tocando el servidor?",
                    "¿Ya fuiste a Mordor o tu producción tiene SSL?",
                    "¿Tus endpoints viajan en el tiempo como Marty McFly?",
                    "¿Tenés más bugs que el Amazonas?",
                    "¿Deployás en viernes o simplemente te gusta el caos?",
                    "¿Tu código compila o le hacés Reiki?",
                    "¿Esa excepción es parte del feature o del folklore del sistema?",
                    "¿Tus test pasan o solo se resignan?",
                    "¿Vivís en modo oscuro por elección o porque tu alma ya es backend?",
                    "¿Debuggeás o simplemente llorás frente al monitor?",
                    "¿Ese warning es normal o ya se volvió parte del equipo?",
                    "¿Tenés CI/CD o es más bien Ctrl+C/Ctrl+V?",
                    "¿Usás Docker o preferís vivir peligrosamente?",
                    "¿Tus microservicios son amigos o ex parejas que no se hablan?",
                    "¿Configuraste bien el DNS o invocaste a Cthulhu por accidente?",
                    "¿Tu documentación está actualizada o es ciencia ficción?",
                    "¿Tu app escala o se descompone como Jenga bajo presión?",
                    "¿Tenés cobertura de tests o vivís al borde del abismo?",
                    "¿Hiciste el deploy con fe, suerte o velas?",
                    "¿Quién autorizó ese `rm -rf /` con tanta confianza?",
                    "¿Tu código es arte o crimen de guerra?",
                    "¿Tu base de datos está normalizada o es una telenovela?",
                    "¿Tu frontend es accesible o hay que hacer un ritual para usarlo?",
                    "¿Vivís en el backlog o tenés residencia fija en el Sprint?",
                    "¿Tu Wi-Fi anda o estás rezando a San Router?",
                    "¿Tu servidor tiene uptime o está haciendo la siesta?",
                    "¿Sos dev, devops, QA o simplemente sobreviviente del sprint?",
                    "¿Tenés control de versiones o versión controlada por el caos?",
                    "¿Tu entorno local es igual al de producción o eso es ciencia ficción?",
                    "¿Es un feature o un bug que aprendió a vivir en sociedad?",
                    "¿Git te ayuda o es tu relación tóxica de todos los días?",
                    "¿Tu scrum master es humano o bot motivacional?",
                    "¿Hiciste el commit con mensaje útil o con ‘arreglo final final 2’?",
                    "¿Tu código funciona o simplemente deja de dar errores por cansancio?",
                    "¿Esa app es responsive o responde con evasivas?",
                    "¿Te tomás breaks o simplemente cambiás de monitor?",
                    "¿Ese `if` tiene lógica o fue inspirado por una película de Nolan?",
                    "¿El código es DRY o más bien Wet: Write Everything Twice?",
                    "¿Tenés entorno de staging o jugás a la ruleta rusa en producción?",
                    "¿Tu API responde o hace ghosting?",
                    "¿Ese CSS es arte moderno o error de tipografía?",
                    "¿Tenés logs o simplemente rezás cuando algo falla?",
                    "¿El sistema está caído o está practicando yoga horizontal?",
                    "¿Ese error es tuyo o legado de un antiguo hechicero?",
                    "¿Quién puso el botón de 'borrar todo' al lado del de 'guardar'?",
                    "¿Ese script automatiza o invoca al caos?",
                    "¿Tu setup es minimalista o vive en una maraña de cables?",
                    "¿Tenés backup o tenés fe?",
                    "¿Sos full stack o solo estás lleno de tareas?",
                    "¿Esa excepción es try/catch o try/cry?",
                    "¿El cliente pidió eso o lo soñaste entre commits?",
                    "¿Tu sistema es monolito o edificio abandonado?",
                    "¿La daily dura 15 minutos o una eternidad espiritual?",
                    "¿Hacés code review o lectura de tarot binario?",
                    "¿Tu PC arranca rápido o medita antes de prenderse?",
                    "¿El cron job anda o está de vacaciones?",
                    "¿Tenés tech debt o directamente hipoteca digital?",
                    "¿Ese JSON es válido o es una criatura ancestral?",
                    "¿Tenés un plan B o simplemente improvisás con estilo?",
                    "¿Sos developer o domador de errores legendarios?",
                    "¿Ese botón hace algo o es placebo UI?",
                    "¿El diseño es Figma o fe y ganas?",
                    "¿Ese bug es nuevo o ya es parte del folklore del sistema?",
                    "¿El router anda o está recordando sus traumas de fábrica?",
                    "¿La demo es real o una coreografía de prints?",
                    "¿Tu IDE es tu amigo o tu secuestrador?",
                    "¿Sos programador o domador de commits fallidos?",
                    "¿El ticket está en Jira o desapareció en el triángulo de las Bermudas?",
                    "¿Tu base de datos tiene relaciones o está más sola que vos un sábado?",
                    "¿Ese `404` es por error o por arte conceptual?",
                    "¿Deployás con confianza o bajo amenaza?",
                    "¿Ese cron job ejecuta algo o está en huelga?",
                    "¿Tus validaciones son estrictas o creen en el poder del amor?",
                    "¿Esa excepción se maneja o solo grita en producción?",
                    "¿Ese script automatiza o sabotea silenciosamente?",
                    "¿El cliente pidió eso o lo interpretaste como Picasso?",
                    "¿Tus commits tienen sentido o son como sueños raros?",
                    "¿Tenés arquitectura o Jenga con código?",
                    "¿Estás en modo debug o crisis existencial?",
                    "¿Ese `.env` está seguro o en Google Drive de todos?",
                    "¿El sistema escala o se infla como globo de feria?",
                    "¿El CSS responde o se rebela?",
                    "¿Hiciste rollback o directamente rezaste?",
                    "¿La documentación está actualizada o es una carta al futuro?",
                    "¿Sos ágil o simplemente corrés sin rumbo?",
                    "¿Tenés sprint o maratón de bugs?",
                    "¿Tu sistema soporta usuarios o se ofende con ellos?",
                    "¿Es un microservicio o un minijefe de nivel?",
                    "¿Ese warning es leve o una señal del apocalipsis?",
                    "¿Tu sesión expira o se jubila?",
                    "¿El código es limpio o le falta un exorcismo?",
                    "¿Usás frameworks o invocaciones oscuras?",
                    "¿El endpoint responde o necesita terapia?",
                    "¿Tenés una arquitectura orientada a servicios o al caos?",
                    "¿El equipo es ágil o velocistas sin mapa?",
                    "¿Ese script se ejecuta o se ilumina espiritualmente?",
                    "¿Tu consola tira logs o indirectas?",
                    "¿La variable es global o emperador universal?",
                    "¿El servidor está caído o sólo tomando mate?",
                    "¿Ese error es técnico o existencial?",
                    "¿El `localhost` es tu reino o tu prisión?",
                    "¿El deploy fue exitoso o una ilusión óptica?",
                    "¿El código es mantenible o campo minado?",
                    "¿Tu commit dice algo o habla en sánscrito?",
                    "¿Ese patch arregla algo o tapa el sol con un `try`?",
                    "¿Tu `git log` cuenta una historia o una tragedia?",
                    "¿El API devuelve datos o misterios?",
                    "¿Sos dev o exorcista de bugs crónicos?",
                    "¿Ese issue es urgente o simplemente grita más fuerte?",
                    "¿Tu sistema se actualiza o se autodestruye lentamente?",
                    "¿Ese bug es nuevo o ya cobra aguinaldo?",
                    "¿Tenés logs o le preguntás al sistema cómo se siente?",
                    "¿El release fue exitoso o una fiesta sorpresa de errores?",
                    "¿Ese servidor responde o se fue a vivir al bosque?",
                    "¿Tus scripts corren o hacen parkour?",
                    "¿El sistema está caído o haciendo yoga de desconexión?",
                    "¿Tenés políticas de seguridad o fe ciega?",
                    "Diablo que maldito teni.",
                    "¿Ese HTML es semántico o simplemente un collage?",
                    "¿Tu documentación es útil o poesía postmoderna?",
                    "¿El error es del código o de la humanidad?",
                    "¿Ese merge fue pacífico o una guerra civil?",
                    "¿Tenés integración continua o conflicto constante?",
                    "¿El repo está ordenado o pide exorcismo digital?",
                    "¿Ese botón guarda o guarda rencor?",
                    "¿Tu framework es liviano o tiene metabolismo lento?",
                    "¿La daily es para alinear o para llorar en grupo?",
                    "¿El build falla o solo te está probando?",
                    "¿El equipo es multidisciplinario o banda de piratas?",
                    "¿Tenés arquitectura modular o patchwork emocional?",
                    "¿El código es legible o escrito en jeroglífico?",
                    "¿El servidor tiene carga o carga con tus decisiones?",
                    "¿Ese frontend es accesible o tenés que ser Jedi para navegarlo?",
                    "¿La conexión es lenta o simplemente tímida?",
                    "¿El dev junior rompió algo o descubrió una dimensión nueva?",
                    "¿El branch está actualizado o es arqueología?",
                    "¿La tarea era simple o simplemente imposible?",
                    "¿Tu código es escalable o escalofriante?",
                    "¿Tenés un diseño UX o un experimento social?",
                    "¿La query es optimizada o un poema épico a la lentitud?",
                    "¿Esa tarea está en progreso o en pausa existencial?",
                    "¿El servidor es dedicado o distraído?",
                    "¿Tus endpoints están protegidos o se sienten abandonados?",
                    "¿Ese `try` captura errores o los ignora con elegancia?",
                    "¿Tenés naming conventions o caos creativo?",
                    "¿Tu código es open source o caja de Pandora?",
                    "¿El sistema hace logging o confesiones?",
                    "¿Esa dependencia es necesaria o una relación tóxica?",
                    "¿Tu sprint tiene metas o sueños?",
                    "¿El sistema responde rápido o está filosofando?",
                    "¿Tu código tiene tests o fe ciega?",
                    "¿La UI es intuitiva o requiere guía espiritual?",
                    "¿Tu entorno es local o locura pura?",
                    "¿El `ping` responde o medita antes de contestar?",
                    "¿Tu equipo hace pair programming o terapia grupal?",
                    "¿Ese error es de sintaxis o de valores?",
                    "¿El sistema es productivo o simplemente simpático?",
                    "¿El feature fue probado o bautizado y lanzado?",
                    "¿Tenés una solución o una teoría optimista?",
                    "¿El repo tiene estructura o memoria emocional?",
                    "¿Tu código es asíncrono o inestable emocionalmente?",
                    "¿Ese cron ejecuta tareas o cumple deseos?",
                    "¿Esa tabla tiene relaciones o está emocionalmente indisponible?",
                    "¿El deploy es automatizado o por ritual chamánico?",
                    "¿Ese warning se ignora o se respeta como a un viejo sabio?",
                    "¿Tu software es open source o caja de sorpresas?",
                    "¿Tu lógica tiene sentido o necesita GPS?",
                    "¿Esa clase es reutilizable o vengativa?",
                    "¿Tenés un roadmap o una lista de sueños?",
                    "¿Ese config es correcto o simplemente optimista?",
                    "¿Esa migración fue suave o una batalla histórica?",
                    "¿Tu sistema es estable o vive en modo ‘mañana vemos’?",
                    "¿El deploy lo hace Jenkins o un becario con fe?",
                    "¿Ese bug es nuevo o ya tiene antigüedad en la empresa?",
                    "¿El código está testeado o solo Dios sabe si funciona?",
                    "¿La arquitectura es modular o una Jenga emocional?",
                    "¿Ese feature está terminado o en estado Schrödinger?",
                    "¿Tenés un roadmap o una lista de deseos en Notion?",
                    "¿Ese warning se ignora o se respeta como a un viejo sabio?",
                    "¿Tu sistema es estable o vive en modo ‘mañana vemos’?",
                    "¿Ese config es correcto o simplemente optimista?",
                    "¿El sistema escala o se quiebra con tres usuarios?",
                    "¿El código está documentado o es un acertijo para futuras generaciones?",
                    "¿El servidor está en la nube o en el sótano de un edificio olvidado?",
                    "¿La red tiene redundancia o rezan cada vez que cae un switch?",
                    "¿El ping es bajo o solo porque el servidor dejó de responder?",
                    "¿El firewall está bien configurado o bloquea hasta al admin?",
                    "¿Esa IP es fija o aparece y desaparece como un fantasma?",
                    "¿Usan VLANs o todo viaja en una sopa de paquetes?",
                    "¿Tenés monitoreo real o solo intuiciones premonitorias?",
                    "¿La VPN protege o es un túnel al infierno?",
                    "¿La configuración del router se respeta o cada uno toca lo que quiere?",
                    "¿Esa query está optimizada o es una carta abierta al DBA?",
                    "¿La base está normalizada o es un caos funcional?",
                    "¿Ese JOIN es necesario o un capricho de otro siglo?",
                    "¿Los índices ayudan o son decoración digital?",
                    "¿El backup es automático o confías en que no pase nada?",
                    "¿Restauraron la base alguna vez o solo en simulacros?",
                    "¿Las migraciones están controladas o son eventos históricos?",
                    "¿Esa tabla tiene claves o es una hoja de Excel disfrazada?",
                    "¿El login es seguro o se accede con 'admin123'?",
                    "¿Usan doble factor o doble esperanza?",
                    "¿Las contraseñas están hasheadas o escritas en un post-it?",
                    "¿Hay auditorías o solo sustos periódicos?",
                    "¿Los roles están bien asignados o cualquiera es admin si se esfuerza?",
                    "¿La app está protegida o es un buffet libre para pentesters?",
                    "¿Tenés logs de seguridad o solo intuiciones cuando algo anda mal?",
                    "¿Los permisos son mínimos o dignos de superusuario?",
                    "¿Cifraron los datos o se confía en la oscuridad del backend?",
                    "¿Los puertos abiertos son los necesarios o todos los de la lista?",
                                                                ]